name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  docker-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Docker compose config
        run: docker compose config
      - name: Verify Dockerfile
        run: |
          if [[ ! -f "Dockerfile" ]]; then
            echo " Dockerfile not found!"
            exit 1
          fi
          echo " Dockerfile exists."


  integration-test:
    runs-on: ubuntu-latest
    needs: docker-check
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Docker compose up
        run: docker compose up -d --wait
      - name: Run API tests
        run: ./tests/api_tests.sh
      - name: Docker compose down
        run: docker compose down


  deploy:
    runs-on: ubuntu-22.04
    needs: integration-test
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Authenticate with Google Cloud using GitHub Secrets
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'assignment-2-450920'
          workload_identity_provider: 'projects/569598913464/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'

      # Configure Docker for Google Artifact Registry
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/assignment-2-450920/fastapi-repo/fastapi-server:v2
